services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workpulse
    ports:
      - "5432:5432"
    volumes:
      - workpulse_pg:/var/lib/postgresql/data

volumes:
  workpulse_pg:
